### ISSUE TITLE
Frontend Support for Load Balancing and Migration/Mobility

### ISSUE THREAD

**Issue by LPardue** [mirjak/draft-kuehlewind-quic-substrate#6]
Frontend Support for Load Balancing and Migration/Mobility section includes statement:

> Terminating not only the transport connection but also the 
security association is especially problematic if the proxy provider under the direct
authority of the services provided but a contracted third party.

I can't parse this, so I think a "is not under" is required somewhere. Or a restructure of the sentence to better highlight the problem.

**Comment by mirjak** [comment]
There is definitely an "is not" missing. Is that any better?

"Terminating not only the transport connection but also the
security association is especially problematic if the proxy provider is not under the direct
authority of the actual service provider but a contracted third party."
