### ISSUE TITLE
Discovery requirements

### ISSUE THREAD

**Issue by LPardue** [mirjak/draft-kuehlewind-quic-substrate#8]
Do we want to add any text about how clients discover proxies. There are a few ways this works today, HTTP often uses WPAD that I finally found an IETF contribution for (!) https://tools.ietf.org/html/draft-ietf-wrec-wpad-01. Although that document didn't get adopted, it led me to find [RFC 3040](https://datatracker.ietf.org/doc/html/rfc3040) which has some nice descriptions of Web-oriented proxies.

**Comment by mirjak** [comment]
Yes, that is actually on my todo list. I was thinking to also mention DHCP or maybe even DNS. If you want to start writing a paragraph at the end, please go ahead. I can then add my though eventually later!

**Comment by mirjak** [comment]
Text added that was provided by Zahed, see PR #13 . However maybe we want to say more
